#!/usr/bin/env python

import rospy

from dynamic_reconfigure.server import Server
from dynamic_reconfigure_example.cfg import ExampleConfig

# Create reconfigure callback
def callback(config, level):
    rospy.loginfo("""Reconfigure Request: {int_param}, {double_param},\ 
          {str_param}, {bool_param}, {size}""".format(**config))

    # Config is returned by the server
    return config

if __name__ == "__main__":
    rospy.init_node("dynamic_reconfigure_example", anonymous = False)
    
    # Bind callback
    srv = Server(ExampleConfig, callback)
    rospy.spin()
